FROM python:alpine

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt 

RUN mkdir endpoints
COPY ./*.py ./
COPY ./endpoints/*.py ./endpoints/

CMD python3 -m uvicorn server:app --host 0.0.0.0 --port 8080